# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://sigeiacademico.itla.edu.do/account/login")
    self.driver.set_window_size(1020, 553)
    self.driver.find_element(By.ID, "email").send_keys("email cambiado")
    self.driver.find_element(By.ID, "password").send_keys("contraseña cambiada")
    self.driver.find_element(By.ID, "btnLogin").click()
  
