# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPlandeestudio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_plandeestudio(self):
    self.driver.get("https://sigeiacademico.itla.edu.do/")
    self.driver.set_window_size(1020, 553)
    self.driver.find_element(By.CSS_SELECTOR, ".color-sass > .hex:nth-child(2) > div:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) > .nav-link")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) > .nav-link").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".nav-item > .active")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
